services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    pull_policy: always
    ports:
      - '7687:7687'
      - '7444:7444'
    volumes:
      - ./memgraph/etc:/etc/memgraph
      - ./memgraph/var/lib:/var/lib/memgraph:rw
      - ./memgraph/var/log:/var/log/memgraph:rw
    command: ['--log-level=TRACE']

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    pull_policy: always
    ports:
      - '3080:3000'
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
